// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package autowired

import (
	"github.com/DkreativeCoders/expunge-file-service/pkg/service/ProcessFile"
)

// Injectors from wire.go:

func AutoWireNewFactoryProcessFile() *ProcessFile.FactoryProcessFile {
	factoryProcessFile := ProcessFile.NewFactoryProcessFile()
	return factoryProcessFile
}
