// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package autowired

import (
	"github.com/DkreativeCoders/expunge-file-service/pkg/service"
)

// Injectors from wire.go:

func AutoWireNewFactoryProcessFile() *service.FactoryProcessFile {
	factoryProcessFile := service.NewFactoryProcessFile()
	return factoryProcessFile
}
